# Generated by Django 3.2.14 on 2022-07-25 09:59

from django.db import migrations, models
import garpix_notify.utils.file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Globals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to=garpix_notify.utils.file.get_file_path, verbose_name='Логотип')),
                ('privacy_policy', models.FileField(blank=True, upload_to=garpix_notify.utils.file.get_file_path, verbose_name='Политика конфиденциальности')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
