# Generated by Django 3.2.14 on 2022-07-20 11:18

import ckeditor_uploader.fields
from django.db import migrations, models
import garpix_utils.file.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='blogpage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='image',
            field=models.ImageField(blank=True, upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
