# Generated by Django 3.2.14 on 2022-07-16 12:54

import ckeditor_uploader.fields
from django.db import migrations, models
import garpix_utils.file.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postlistpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='image',
            field=models.ImageField(blank=True, upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='Изображение'),
        ),
    ]
