# Generated by Django 3.2.14 on 2022-07-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220717_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
